[package]
name = "dusty"
version = "0.1.1"
edition = "2024"

[dependencies]
crossterm = "0.27.0"
ratatui = "0.26.3"
rayon = "1.8"
walkdir = "2.4"
serde = { version = "1", features = ["derive"] }
serde_json = "1.0"
clap = { version = "4.3", features = ["derive"] }
